### PR TITLE
Make the interactive rings in rviz work again

### PR DESCRIPTION
**Pull request by civerachb-cpr**
Disable the mag data in the simulation; the imu filter is timing out waiting for data, which is disabling the heron_control node, making the robot permanently immobile.  See RPSW-474.

### CODE REVIEW

**Comment by civerachb-cpr** [comment]
Update: rather than disabling the magnetometer data, I've added a new node to translate from the deprecated Vector3Stamped messages the gazebo sensor plugin provides and republish them as MagneticField messages.  This seems to fix the problem the IMU filter was having.

The Gazebo plugin now publishes on /imu/mag_raw, and the new node republishes to /imu/mag, as-per https://github.com/heron/heron/pull/10

**Comment by tonybaltovski** [comment]
Looks good @civerachb-cpr, need to install this script though.  Minor nit would be to drop the `.py` and use underscores for the file name.

**Comment by civerachb-cpr** [comment]
I'd actually added the .py to be consistent with the rest of the scripts in the package. But I've cleaned up all of them now, and fixed the install

**Comment by tonybaltovski** [comment]
Amazing, thanks Chris!

**Review by tonybaltovski — APPROVED** [review]

**Pull request merged**
